const products = require('express').Router()
const productsController = require('./products.controller')
const authMiddleware = require('../../middleware/authMiddleware')
products.get('/', productsController.getAllProducts)
products.get('/latest/:limit', productsController.getLatestProducts)
products.get('/by-category/:category', productsController.getProductsByCategory)
products.get('/categories', productsController.getAllCategories)
products.get('/query', productsController.getProductsByNameOrId)
products.get('/search', productsController.search)
// products.post('/', productsController.addProduct)
products.put('/:id', authMiddleware, productsController.updateProduct)
products.delete('/:id', authMiddleware, productsController.deleteProduct)
products.post('/review', authMiddleware, productsController.addReviewToProduct)
products.post('/upload-image', productsController.uploadImage)
products.get('/scrapping', productsController.scrapProducts)

module.exports = products
